apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: kubernetes-provider
spec:
  credentials:
    secretRef:
      key: kubeconfig
      name: cluster-config
      namespace: crossplane-system
    source: Secret

#apiVersion: kubernetes.crossplane.io/v1alpha1
#kind: ProviderConfig
#metadata:
#  name: kubernetes-provider
#spec:
#  credentials:
#    source: InjectedIdentity
