---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: crossplane-add-on
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: crossplane
  namespace: flux-system
spec:
  chart:
    spec:
      chart: chart
      interval: 1m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: crossplane
        namespace: flux-system
  interval: 1m0s
  targetNamespace: crossplane-system
  values:
    args:
      - --enable-environment-configs
      - --enable-external-secret-stores

