apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: crossplane-add-on
  namespace: flux-system
spec:
  interval: 1m0s
  path: /cluster/add-ons/crossplane
  postBuild:
    substituteFrom:
      - kind: Secret
        name: subvars
  prune: true
  sourceRef:
    kind: GitRepository
    name: add-ons
